# Env var names
ENV_GITHUB_PAT = "INPUT_GITHUB_PAT"
ENV_DATA_DIR = "INPUT_DATA_DIR"
ENV_EXTERNAL_CONTRIBUTIONS_FILE = "INPUT_EXTERNAL_CONTRIBUTIONS_FILE"

# API and rate limits
API_REQUEST_DELAY_SEC = 1
RATE_LIMIT_BUFFER_SEC = 60
RATE_LIMIT_MAX_AGE_SEC = 30
MAX_RETRIES = 0

# Files
CONTRIBUTIONS_FILENAME = "contributions.json"
EXTERNAL_CONTRIBUTIONS_FILENAME = "external_contributions.json"
PEOPLE_FILENAME = "people.json"
