# Env var names
ENV_GITHUB_PAT = "GITHUB_PAT"
ENV_OUTPUT_DATA_DIR = "OUTPUT_DATA_DIR"

# API and rate limits
API_REQUEST_DELAY_SEC = 0.01
RATE_LIMIT_BUFFER_SEC = 60
RATE_LIMIT_MAX_AGE_SEC = 30
MAX_RETRIES = 0

# Files
CONTRIBUTIONS_FILENAME = "contributions.json"
EXTERNAL_CONTRIBUTIONS_FILENAME = "external_contributions.json"
PEOPLE_FILENAME = "people.json"
